version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-student-library
    volumes:
      - ./mongo:/data/db
